extends Node
## NameDB — autoload singleton
##
## Loads data/names.json (generated by tools/extract_names.py) once at startup
## and provides fast random name generation for NPCs.
##
## API:
##   NameDB.random_first_name() -> String
##   NameDB.random_last_name()  -> String
##   NameDB.random_full_name()  -> String   # "FirstName LastName"

const _DATA_PATH := "res://data/names.json"

var _first_names: PackedStringArray = []
var _last_names:  PackedStringArray = []
var _loaded:      bool              = false


func _ready() -> void:
	_load()


func _load() -> void:
	if not FileAccess.file_exists(_DATA_PATH):
		push_warning("NameDB: %s not found — run tools/extract_names.py first." % _DATA_PATH)
		return

	var file := FileAccess.open(_DATA_PATH, FileAccess.READ)
	if file == null:
		push_error("NameDB: could not open %s" % _DATA_PATH)
		return

	var json := JSON.new()
	var err   := json.parse(file.get_as_text())
	file.close()

	if err != OK:
		push_error("NameDB: JSON parse error in %s — %s" % [_DATA_PATH, json.get_error_message()])
		return

	var data: Dictionary = json.get_data() as Dictionary
	var fn_arr: Array    = data.get("first_names", []) as Array
	var ln_arr: Array    = data.get("last_names",  []) as Array

	_first_names.resize(fn_arr.size())
	for i: int in range(fn_arr.size()):
		_first_names[i] = fn_arr[i]

	_last_names.resize(ln_arr.size())
	for i: int in range(ln_arr.size()):
		_last_names[i] = ln_arr[i]

	_loaded = true
	print("NameDB: loaded %d first names, %d last names." % [_first_names.size(), _last_names.size()])


## Returns a random first name.
func random_first_name() -> String:
	if _first_names.is_empty():
		return "Alex"
	return _first_names[randi() % _first_names.size()]


## Returns a random last name.
func random_last_name() -> String:
	if _last_names.is_empty():
		return "Smith"
	return _last_names[randi() % _last_names.size()]


## Returns a random "FirstName LastName" string.
func random_full_name() -> String:
	return random_first_name() + " " + random_last_name()
